### ISSUE TITLE
Adjust the module to not require pre-releases

### ISSUE THREAD

**Issue by cmfcmf** [zikula/CoreManagerModule#15]

**Comment by craigh** [comment]
is this fixed? I just released 1.4.2 with no such requirement?

**Comment by cmfcmf** [comment]
It is still not fixed, but hardcoded: https://github.com/zikula/CoreManagerModule/blob/5ac97aa26086b706e750230ce71a4d0673a54015/Manager/GitHubApiWrapper.php#L90 :smile:

**Comment by craigh** [comment]
appears to be corrected by 7f4f8866739010a6c186ab6bc7968790275042e2
